keys:
  - &avn B0B8FA16CFB715FA0FA746B3B8AF18ABCA6271D2
  - &bulldozer aad88f241a42255dff9d94c4ef7f0d01a36662bb 

creation_rules:
  - path_regex: ^secrets/bulldozer/wireguard/.+\.wg$
  - key_groups:
    - pgp:
      - *avn
      - *bulldozer
  
