{ config, pkgs, ... }:

let writeConf = name: text: pkgs.writeTextFile {
      inherit name text;
      destination = "/etc/cups/${name}";
    };
    printerConf = writeConf "printers.conf" ''
      # DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING
      <DefaultPrinter LaserJet>
      UUID urn:uuid:9257250f-bcfa-36a3-6c27-c649c388593b
      Info 
      Location 
      MakeModel HP LaserJet Series PCL 4/5
      DeviceURI ipp://printer/ipp
      State Idle
      StateTime 1475599524
      ConfigTime 1475599534
      Type 12356
      Accepting Yes
      Shared Yes
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy stop-printer
      </DefaultPrinter>
    '';
in {
  # Enable CUPS to print documents.
  services.printing = {
      enable = true;
      drivers = [ printerConf ];
  };
}
